### PR TITLE
fix: use correct namespace for password secret

### LINKED ISSUE #1578: Can't create a connection string secret in a different namespace
**What did you do to encounter the bug?**

1. Create a kind cluster
2. Install MongoDB Kubernetes Operator on the `mongodb` namespace (set to watch all namespaces in the cluster)
    - `helm repo add mongodb https://mongodb.github.io/helm-charts`
    - `helm install community-operator mongodb/community-operator --namespace mongodb --create-namespace --set operator.watchNamespace="*"`
3. Apply [this manifest](https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/fcf570ef6d2dba41e3e7d7db40034d3f8501cc77/manifest.yaml). Version with syntax highlighting available [here](https://gist.github.com/limwa/f5c507000ba48edcae238134b49b0af3#file-manifest-yaml).
4. Watch the `testing` namespace for new secrets being created.
    - `kubectl get secret -n testing -w --output-watch-events`
5. No connection string secrets are created in the `testing` namespace, even after the MDBC resource reaches the "Running" phase.
6. Read the operator logs. There is a message saying the secret "mongodb-apps-testinguser-credentials" could not be found.

**What did you expect?**

I expected a connection string secret with the name "testinguser-mongodb-secret" in the "testing" namespace to be created, after the MDBC resource reached the "Running" phase.

**What happened instead?**

No connection string secret was created in the "testing" namespace, even after the MDBC resource reached the "Running" phase. This only happened for the "testinguser". The "adminuser", which doesn't specify the "connectionStringSecretNamespace" parameter, had its connection string secret created in the `mongodb` namespace.

**Operator Information**
 - Operator Version: 0.10.0 from quay.io
 - MongoDB Image used: [7.0.12 from docker.io](https://hub.docker.com/layers/library/mongo/7.0.12/images/sha256-24ecfe95bbb98cd49e1d968c204515d4033ef86621e68ce148cf1d0a5a0f8a82?context=explore)

**Kubernetes Cluster Information**
 - Distribution: Kind
 - Version: v1.27.3
 - Image Registry location: not sure - according to the helm chart, mongodb comes from docker.io, and agent, versionUpgradeHook, readinessProbe and operator come from quay.io  

**Additional context**

If I add the `mongodb-apps-testinguser-credentials` secret to **both** the `mongodb` and the `testing` namespaces, the `testinguser-mongodb-secret` secret is created in the `testing` namespace, however, it is instantly deleted.

If I only create the `mongodb-apps-testinguser-credentials` secret in the `testing` namespace, the MDBC resource never reaches the "Running" phase.

Operator Logs: https://gist.github.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/934bcc1016e6a2f935c576a0a7557a5452d7beaf/operator-logs.txt

`kubectl get sts -n mongodb -oyaml`: https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/e712f778aa27e37daa361284e633301853099629/sts-out.yaml

`kubectl get pods -n mongodb -oyaml`: https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/e712f778aa27e37daa361284e633301853099629/pods-out.yaml

Regarding the `mongodb-apps-0` pod (all pods seem fine, I just chose this one because it was the first one):
 - Logs: https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/e712f778aa27e37daa361284e633301853099629/pod-logs.txt
 - The agent clusterconfig: https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/e712f778aa27e37daa361284e633301853099629/cluster-config.json
 - The agent health status: https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/e712f778aa27e37daa361284e633301853099629/agent-health-status.json
 - The verbose agent logs of the faulty members: https://gist.githubusercontent.com/limwa/f5c507000ba48edcae238134b49b0af3/raw/e712f778aa27e37daa361284e633301853099629/automation-agent-verbose.log

### PR DESCRIPTION
**Pull request by limwa**
### Summary:

Closes #1578.

I created this PR because, in our deployment of mongodb-kubernetes-operator at NIAEFEUP, we were having trouble creating the connection string secret in a namespace that was not the one the MDBC resource was deployed to. In particular, as described in the issue, one problem that we encountered was needing to have the password secret in both namespaces (the MDBC resource namespace and the connectionStringSecretNamespace namespace) for the connection string secret to be created. The logic was changed so that the password secret is always looked up in the namespace of the MDBC resource.

As a result, the password secret now only needs to be on the namespace of the MDBC resource (as was expected by the `ensureUserResources` function).

### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by limwa** [comment]
Regarding the problem with the connection string secret being garbage-collected when the operator is not deployed cluster-wide, as described in #1578, this PR doesn't fix that problem, because it is unrelated to the logic changed in this PR.

**Comment by legal90** [comment]
Thank you for submitting this fix, @limwa!  Looking forward for MongoDB to review and release it soon :)

P.s. I run into the same issue recently, mentioned it here: https://github.com/mongodb/mongodb-kubernetes-operator/commit/f904443b352455d8d44a0eb3a5e3db6933b8d1df#r143621651

**Review by slaskawi — CHANGES_REQUESTED** [review]
Thanks for the fix attempt. Could you please check my comment?

File: controllers/mongodb_users.go [hunk 1]
```diff
@@ -62,7 +62,7 @@ func (r ReplicaSetReconciler) updateConnectionStringSecrets(ctx context.Context,
 		pwd := ""
 
 		if user.Database != constants.ExternalDB {
-			secretNamespacedName := types.NamespacedName{Name: user.PasswordSecretName, Namespace: secretNamespace}
+			secretNamespacedName := types.NamespacedName{Name: user.PasswordSecretName, Namespace: mdb.Namespace}
```
Comment (slaskawi) [inline controllers/mongodb_users.go:65]: This doesn't seem correct. In fact, the `secretNamespace` maps to `mdb.Namespace`.

Comment (limwa) [reply controllers/mongodb_users.go:65]: secretNamespace maps to mdb.Namespace unles a connectionStringSecretNamespace is provided, in which case it maps to connectionStringSecretNamespace.

Furthermore, in the ensureUserResources function, the password secret is looked up only in mdb.Namespace.

This mismatch between functions (this function looks up on one of the two and the ensure user resources looks up on only one of them) causes the problem described in the issue.

Comment (slaskawi) [reply controllers/mongodb_users.go:65]: You're absolutely right! Thanks for explaining.

**Review by slaskawi — APPROVED** [review]
LGTM. Scheduled a CI run for this one.

**Comment by slaskawi** [comment]
Integrated! Thanks for contribution!

**Comment by realtimetodie** [comment]
@slaskawi Could you please make a release that includes this bugfix? This is urgently needed🙏 thank you
