### PR TITLE
CLOUDP-82639: ARM support

### LINKED ISSUE #299: Not able to run the image on aarch64
I think the issue has to do with the aarch64 on my Raspberry Pi.
Maybe the image is not built for this architecture?
If you could give me a "How-to build" I will be more than happy to try and see if that's the case.

The image "runs" on MacOS and returns an error that variables are missing which is totally understandable.

**What did you do to encounter the bug?**
1. Start the container on a Raspberry Pi
2. Run the Docker Container `docker run quay.io/mongodb/mongodb-kubernetes-operator:0.4.0` or via Kubernetes

**What did you expect?**
A running container or the same error as on MacOS when started without parameters.

**What happened instead?**
I received the following error and the container crashed.
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Operator Information**
 - Operator Version: 0.4.0
 - MongoDB Image used: none

**Kubernetes Cluster Information**
 - Distribution: K3S
 - Version: v1.20.2+k3s1
 - Image Registry location (quay, or an internal registry)

**Additional context**
Raspberry Pi 4B
Ubuntu 20.04.1
aarch64

### PR DESCRIPTION
**Pull request by lucian-tosa**
Closes #299 

### Summary

The image building process will use the same dockerfile for both of architectures. The dockerfiles have been updated to accommodate for any target platform. Like before, we use sonar to build docker images, but now, sonar is used twice to build an image for both amd64 and arm64 architecture. Thus resulting in images with the suffix '-amd64' and '-arm64'. 
After building the images, the method `create_and_push_manifest` will use the created images with the architecture suffix and combine them in a manifest which is then pushed to the quay.io registry. This manifest is the final multi-arch image. In the end, the users will be able to pull the same image tag and get the appropriate image for their architecture, thus, it will work ootb for both architectures.

Here is an interesting blog about this: https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/ 

### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by mohsinonxrm** [comment]
@lucian-tosa , thanks for getting this going. However, I've got a few questions, since I've generated ARM64 versions of this before but never really got the time to complete the actions etc. 

When I built the images, I ran into an issue where the automation config builder was missing aarch64, so I had to update that function:
https://github.com/mongodb/mongodb-kubernetes-operator/blob/arm-support/pkg/automationconfig/automation_config_builder.go#L423

For reference, please review this:
https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-1304565428

Also, I haven't reviewed the https://github.com/mongodb/mongodb-kubernetes-operator/blob/arm-support/inventory.yaml in detail but won't you need to build arm64 version for the agent as well?

Please note that for the automation agent (arm64/aarch64) you'll need to provide amzn2_aarch64 as the agent distro.

Anyway, looking forward to this working and getting official support!

File: test/e2e/setup/test_config.go [hunk 1]
```diff
@@ -36,8 +36,8 @@ func LoadTestConfigFromEnv() TestConfig {
 		CertManagerNamespace:    envvar.GetEnvOrDefault(testCertManagerNamespaceEnvName, "cert-manager"),
 		CertManagerVersion:      envvar.GetEnvOrDefault(testCertManagerVersionEnvName, "v1.5.3"),
 		OperatorImage:           envvar.GetEnvOrDefault(operatorImageEnvName, "quay.io/mongodb/community-operator-dev:latest"),
-		MongoDBImage:            envvar.GetEnvOrDefault(construct.MongodbName, "mongodb-community-server"),
-		MongoDBRepoUrl:          envvar.GetEnvOrDefault(construct.MongodbRepoUrl, "docker.io/mongodb"),
+		MongoDBImage:            envvar.GetEnvOrDefault(construct.MongodbImageEnv, "mongo"),
```
Comment (irajdeep) [inline test/e2e/setup/test_config.go:39]: I believe we want to use the official image here shipped by Mongo.

Comment (lucian-tosa) [reply test/e2e/setup/test_config.go:39]: Sure! I was thinking of making it more consistent since the helm charts use these images instead. But for testing it doesn't make a difference.

File: pipeline.py [hunk 2]
```diff
@@ -143,6 +235,61 @@ def build_e2e_image(config: DevConfig) -> None:
...
+    args = ["docker", "manifest", "push", final_manifest]
+    args_str = " ".join(args)
+    print(f"pushing new manifest: {args_str}")
+    cp = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+
+    if cp.returncode != 0:
+        raise Exception(cp.stderr)
+
+
+# docker manifest rm $(REPO_URL)/$(OPERATOR_IMAGE):latest | true
```
Comment (mircea-cosbuc) [inline pipeline.py:290]: These steps should be part of the docstring for the above function, right?

**Review by nammn — COMMENTED** [review]
lgtm! Can we add a small implementation summary of whats the input. output and how things tie together? Since its mostly configurational changes

File: pipeline.py (hunk 2 above)
Comment (lucian-tosa) [reply pipeline.py:290]: Oh yes, they describe what this method does. Do you think I should put them above the function, or delete them entirely?

[the remark this answers is not in the document]
Comment (lucian-tosa) [reply pipeline.py:290]: It just describes what commands this function runs, but they could be removed.

**Review by mircea-cosbuc — APPROVED** [review]
Nice work! LGTM

File: pipeline.py (hunk 2 above)
Comment (mircea-cosbuc) [reply pipeline.py:290]: I think they should go above the function, maybe extend with a docstring, saying this does the equivalent of these commands.

Comment (lucian-tosa) [reply pipeline.py]: Yes, done!

[the remark this answers is not in the document]
Comment (lucian-tosa) [reply pipeline.py]: Done!

File: pipeline.py [hunk 3]
```diff
@@ -252,6 +252,17 @@ def build_e2e_image(config: DevConfig) -> None:
...
+"""
+generates docker manifests by running the following commands:
+1. Clear existing manifests
+docker manifest rm config.repo_url/image:tag
+2. Create the manifest
+docker manifest create config.repo_url/image:tag --amend config.repo_url/image:tag-amd64 --amend config.repo_url/image:tag-arm64
+3. Push the manifest
+docker manifest push config.repo_url/image:tag
+"""
+
```
Comment (nammn) [inline pipeline.py:264]: can we make it directly above the func (I also prefer above, but I believe pep python says it should be under, for me its fine either way as long as its consistent)?

Comment (lucian-tosa) [reply pipeline.py:264]: It looks like the pre-commit hook did that. Should I disable it for this?

Comment (nammn) [reply pipeline.py:264]: Oh, let me check that. Don't worry about that then

Comment (nammn) [reply pipeline.py:264]: Ah I believe its probably because that docstring is above the function which black does not recognize and therefore it adds those \n. 

Could you test adding that directly below the func and run the pre-commit again?

Comment (lucian-tosa) [reply pipeline.py:264]: Still adds whitespace even below.

Comment (nammn) [reply pipeline.py:264]: Hm, then feel free to keep it above, I will check at some point why this is the case 😓

**Review by irajdeep — APPROVED** [review]

**Comment by vramperez** [comment]
I am testing the new release 0.8.3 and I have detected that at least two images do not comply with having a single tag with a manifest for both architectures (arm and amd). More specifically, the images `quay.io/mongodb/mongodb-agent:12.0.25.7724-1` and `quay.io/mongodb/mongodb-kubernetes-operator:0.8.3` seem to have the manifest only support for amd architecture:
```
docker manifest inspect --verbose quay.io/mongodb/mongodb-agent:12.0.25.7724-1
{
	"Ref": "quay.io/mongodb/mongodb-agent:12.0.25.7724-1",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:ae9a33c87fc623985b26140ed93bb2ea510fd3682279ea50770f9c4d47b20b2c",
		"size": 2004,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
	},
	"Raw": "ewogICAic2NoZW1hVmVyc2lvbiI6IDIsCiAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5kaXN0cmlidXRpb24ubWFuaWZlc3QudjIranNvbiIsCiAgICJjb25maWciOiB7CiAgICAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5jb250YWluZXIuaW1hZ2UudjEranNvbiIsCiAgICAgICJzaXplIjogNDkyNiwKICAgICAgImRpZ2VzdCI6ICJzaGEyNTY6NGQ0NTY1OTFkOGMzNzE2YjE5YjJiZTc0NzE2ZmFjYWY1YTRlMDM3MGVkNGJlZGFhM2ZiOWE0YjA5M2FiMGIxZSIKICAgfSwKICAgImxheWVycyI6IFsKICAgICAgewogICAgICAgICAibWVkaWFUeXBlIjogImFwcGxpY2F0aW9uL3ZuZC5kb2NrZXIuaW1hZ2Uucm9vdGZzLmRpZmYudGFyLmd6aXAiLAogICAgICAgICAic2l6ZSI6IDI4NTgwNjcxLAogICAgICAgICAiZGlnZXN0IjogInNoYTI1Njo3MDA3NDkwMTI2ZWZhYWU1ODkyNDk3MjY2ODI1NmFhZWI0ODU4ZTZjNDUzN2ViNDI1N2UxOTc4NzE5Yjk1OGM3IgogICAgICB9LAogICAgICB7CiAgICAgICAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5pbWFnZS5yb290ZnMuZGlmZi50YXIuZ3ppcCIsCiAgICAgICAgICJzaXplIjogMTMzNDk0MzYsCiAgICAgICAgICJkaWdlc3QiOiAic2hhMjU2OjA4OWFjODc1MWUyZjBmMjM1OWIwMjUwYzNlNjg2M2U4YmFkMWNkOWZiYTc2Zjc1ZDRhMTQ5NWNmYzQ0OWFlNDUiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAgIm1lZGlhVHlwZSI6ICJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmltYWdlLnJvb3Rmcy5kaWZmLnRhci5nemlwIiwKICAgICAgICAgInNpemUiOiAyMjIsCiAgICAgICAgICJkaWdlc3QiOiAic2hhMjU2OjUwNTU3ZjU1NDFkZmY4Y2FkM2I2ZjhkY2ViOWVjZTAyZTJmMDlmNmYzYTRmZGJmMGQ0ZjhjNjRjNDUyYTY3NTciCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAgIm1lZGlhVHlwZSI6ICJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmltYWdlLnJvb3Rmcy5kaWZmLnRhci5nemlwIiwKICAgICAgICAgInNpemUiOiAzOTcwOTMwMSwKICAgICAgICAgImRpZ2VzdCI6ICJzaGEyNTY6Y2JiNzdlZWQxZTUyYmU1MmQwZjY5YzcxZmVjNGMxMGIwZWNlNDJiMTUxNzMyNWM2MDYwODUzMjkyZjRkOTRmMyIKICAgICAgfSwKICAgICAgewogICAgICAgICAibWVkaWFUeXBlIjogImFwcGxpY2F0aW9uL3ZuZC5kb2NrZXIuaW1hZ2Uucm9vdGZzLmRpZmYudGFyLmd6aXAiLAogICAgICAgICAic2l6ZSI6IDU5NzkwOTMxLAogICAgICAgICAiZGlnZXN0IjogInNoYTI1NjozNWY5NTI5YmM5YzMzOWRjNTc0NzIwZTViYTcxMzVhYTBkZDllYjVmODkyNjk1OTFlOTdlZWU2N2JiYjM3YmE1IgogICAgICB9LAogICAgICB7CiAgICAgICAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5pbWFnZS5yb290ZnMuZGlmZi50YXIuZ3ppcCIsCiAgICAgICAgICJzaXplIjogMzUwNSwKICAgICAgICAgImRpZ2VzdCI6ICJzaGEyNTY6ZWI1MjQ1Y2IwOTJhODU5OWM5NDJjMTQyOWE1OGFhZjI4N2JkNmE0MDdkNWM3NDBhMDliNTVkYWQwZmNkZTM1MyIKICAgICAgfSwKICAgICAgewogICAgICAgICAibWVkaWFUeXBlIjogImFwcGxpY2F0aW9uL3ZuZC5kb2NrZXIuaW1hZ2Uucm9vdGZzLmRpZmYudGFyLmd6aXAiLAogICAgICAgICAic2l6ZSI6IDM4MzM1ODM4LAogICAgICAgICAiZGlnZXN0IjogInNoYTI1NjoyYmRjYzYxYmIzMzI4YWNhZmNlZGVlYmU5ZDI2ZmYwNzFiYWEyNmZjZTBlMzcxYWY2MjgxOTY4YTgzMmM3OWQwIgogICAgICB9LAogICAgICB7CiAgICAgICAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5pbWFnZS5yb290ZnMuZGlmZi50YXIuZ3ppcCIsCiAgICAgICAgICJzaXplIjogNjAwMjA4NzgsCiAgICAgICAgICJkaWdlc3QiOiAic2hhMjU2OjM0MjA3ZTA2NjUzM2EzZWZhOGFkNmU2ZmE0ODJmYjNhYmY2YjljNWQ5Nzk0YjA5MDkxMjAyNTlkNmIwNTJhOTgiCiAgICAgIH0KICAgXQp9",
	"SchemaV2Manifest": {
		"schemaVersion": 2,
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"config": {
			"mediaType": "application/vnd.docker.container.image.v1+json",
			"size": 4926,
			"digest": "sha256:4d456591d8c3716b19b2be74716facaf5a4e0370ed4bedaa3fb9a4b093ab0b1e"
		},
		"layers": [
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 28580671,
				"digest": "sha256:7007490126efaae58924972668256aaeb4858e6c4537eb4257e1978719b958c7"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 13349436,
				"digest": "sha256:089ac8751e2f0f2359b0250c3e6863e8bad1cd9fba76f75d4a1495cfc449ae45"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 222,
				"digest": "sha256:50557f5541dff8cad3b6f8dceb9ece02e2f09f6f3a4fdbf0d4f8c64c452a6757"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 39709301,
				"digest": "sha256:cbb77eed1e52be52d0f69c71fec4c10b0ece42b1517325c6060853292f4d94f3"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 59790931,
				"digest": "sha256:35f9529bc9c339dc574720e5ba7135aa0dd9eb5f89269591e97eee67bbb37ba5"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 3505,
				"digest": "sha256:eb5245cb092a8599c942c1429a58aaf287bd6a407d5c740a09b55dad0fcde353"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 38335838,
				"digest": "sha256:2bdcc61bb3328acafcedeebe9d26ff071baa26fce0e371af6281968a832c79d0"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 60020878,
				"digest": "sha256:34207e066533a3efa8ad6e6fa482fb3abf6b9c5d9794b0909120259d6b052a98"
			}
		]
	}
}
```
```
docker manifest inspect --verbose quay.io/mongodb/mongodb-kubernetes-operator:0.8.3
{
	"Ref": "quay.io/mongodb/mongodb-kubernetes-operator:0.8.3",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:b5e3cabf897746fd46a63d8b24aa0c8993ff7e77cea0f16b5d780275121044fd",
		"size": 1155,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
	},
	"Raw": "ewogICAic2NoZW1hVmVyc2lvbiI6IDIsCiAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5kaXN0cmlidXRpb24ubWFuaWZlc3QudjIranNvbiIsCiAgICJjb25maWciOiB7CiAgICAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5jb250YWluZXIuaW1hZ2UudjEranNvbiIsCiAgICAgICJzaXplIjogNzYxNCwKICAgICAgImRpZ2VzdCI6ICJzaGEyNTY6ZDBkNmM3NThiMWE2NjY4ODIyNGUxMzNkNDg2MzY1ZmUxYTk4Y2M0OWYwY2MzYTM1YWQyOTAwZjczYjg1ZTA0MSIKICAgfSwKICAgImxheWVycyI6IFsKICAgICAgewogICAgICAgICAibWVkaWFUeXBlIjogImFwcGxpY2F0aW9uL3ZuZC5kb2NrZXIuaW1hZ2Uucm9vdGZzLmRpZmYudGFyLmd6aXAiLAogICAgICAgICAic2l6ZSI6IDM3MDA3NjkzLAogICAgICAgICAiZGlnZXN0IjogInNoYTI1NjoyYWFiOGYyNjhlODIwOTJjMGVlNDE4ZmY2MjZmODYwMTJmODQzYmE0MDc0N2UzMzA4MTdiOWUyZjdlYzMzODViIgogICAgICB9LAogICAgICB7CiAgICAgICAgICJtZWRpYVR5cGUiOiAiYXBwbGljYXRpb24vdm5kLmRvY2tlci5pbWFnZS5yb290ZnMuZGlmZi50YXIuZ3ppcCIsCiAgICAgICAgICJzaXplIjogMjE4MzEzNDksCiAgICAgICAgICJkaWdlc3QiOiAic2hhMjU2OmUzNTc3YTY1Yzg4OTJiM2U1MjgzZTU2NjU2Njc2MWEyNjhkN2ZkNDdlNDFiMjdkMTk3NjczMmQ0MzZjZjcwNzYiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAgIm1lZGlhVHlwZSI6ICJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmltYWdlLnJvb3Rmcy5kaWZmLnRhci5nemlwIiwKICAgICAgICAgInNpemUiOiA2ODMsCiAgICAgICAgICJkaWdlc3QiOiAic2hhMjU2OjEwYmM2OTA5NmY4ZDNjZTY5YjRhYzExNDAwYTZiZmIxOTkyMjNiYmViOTRiZmZkMmMyZWY4NWZmNjNmMWY4ZDciCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAgIm1lZGlhVHlwZSI6ICJhcHBsaWNhdGlvbi92bmQuZG9ja2VyLmltYWdlLnJvb3Rmcy5kaWZmLnRhci5nemlwIiwKICAgICAgICAgInNpemUiOiA0NjQsCiAgICAgICAgICJkaWdlc3QiOiAic2hhMjU2OjIzNmUwMjZlYWE2NGMzN2UyZGRjNjdjYjM0MTEzZGUzYmU0ZDRmYTE0MWJkZGYwN2NhMjBlNDU2MGUwNzg4ZGIiCiAgICAgIH0KICAgXQp9",
	"SchemaV2Manifest": {
		"schemaVersion": 2,
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"config": {
			"mediaType": "application/vnd.docker.container.image.v1+json",
			"size": 7614,
			"digest": "sha256:d0d6c758b1a66688224e133d486365fe1a98cc49f0cc3a35ad2900f73b85e041"
		},
		"layers": [
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 37007693,
				"digest": "sha256:2aab8f268e82092c0ee418ff626f86012f843ba40747e330817b9e2f7ec3385b"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 21831349,
				"digest": "sha256:e3577a65c8892b3e5283e566566761a268d7fd47e41b27d1976732d436cf7076"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 683,
				"digest": "sha256:10bc69096f8d3ce69b4ac11400a6bfb199223bbeb94bffd2c2ef85ff63f1f8d7"
			},
			{
				"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
				"size": 464,
				"digest": "sha256:236e026eaa64c37e2ddc67cb34113de3be4d4fa141bddf07ca20e4560e0788db"
			}
		]
	}
}
```

The operator image seems to have a specific tag for arm (`quay.io/mongodb/mongodb/mongodb-kubernetes-operator:0.8.3-arm64`), but the mongodb-agent image doesn't (or I haven't found it).

If this is confirmed, I think it defeats the purpose of this issue of "If this is confirmed, I think it fails to meet the purpose of this issue of "In the end, the users will be able to pull the same image tag and get the appropriate image for their architecture, thus, it will work ootb for both architectures".

**Comment by abasu0713** [comment]
any update here? `mongodb-agent` still fails on arm64

**Comment by Julien-Ben** [comment]
Hi @abasu0713,
Can you please try using these multi-arch images:
https://quay.io/repository/mongodb/mongodb-agent-ubi

and let me know if it solves your problem ?

**Comment by abasu0713** [comment]
> Hi @abasu0713,
> Can you please try using these multi-arch images:
> https://quay.io/repository/mongodb/mongodb-agent-ubi
> 
> and let me know if it solves your problem ?
> 

All good. It works with the ubi agent just fine! Thank you. Just a tiny recommendation for the documentation on the Operator be updated for Arm specific instructions. It could even be put as comments in the Operator helm chart values.
