### PR TITLE
Test connection string works when mounted into pod

### LINKED ISSUE #878: connection string from secret does not work unmodified
**What did you do to encounter the bug?**
1, Install the operator and create a replica set
2. Install a instance of mongo express - pulling the connection string from the created secret 
```  
 - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: connectionString.standard
              name: cluster-mongodb-admin-manager
```
3. mongo express logs this error 
```
Could not connect to database using connectionString: mongodb://manager:password@cluster-mongodb-0.cluster-mongodb-svc.mongodb.svc.cluster.local:27017,cluster-mongodb-1.cluster-mongodb-svc.mongodb.svc.cluster.local:27017,cluster-mongodb-2.cluster-mongodb-svc.mongodb.svc.cluster.local:27017/admin?ssl=false"
UnhandledPromiseRejectionWarning: MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URL
```

**What did you expect?**
I expected the connection string to work out the box

**What happened instead?**
I needed to update the connectionString to append `&replicaSet=cluster-mongodb` to the end, at which point it started working.
 
**Operator Information**
 - Operator Version: :0.7.2
 - MongoDB Image used: 5.0.6

### PR DESCRIPTION
**Pull request by chatton**
### All Submissions:

closes #878

We weren't correctly specifying the replica set name in the generated connection strings. This PR adds a small test app which connects using both the regular connection string as well as the srv connection string.

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [X] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by eugene-marchanka** [comment]
looking forward for this change

File: test/e2e/util/wait/wait.go [hunk 1]
```diff
@@ -181,6 +181,17 @@ func ForPodReadiness(t *testing.T, isReady bool, containerName string, timeout t
 	})
 }
 
+func ForPodPhase(t *testing.T, timeout time.Duration, pod corev1.Pod, podPhase corev1.PodPhase) error {
```
Comment (irajdeep) [inline test/e2e/util/wait/wait.go:184]: Can we add a comment to this function like other methods?

**Review by irajdeep — APPROVED** [review]
LGTM
