### PR TITLE
CLOUDP-83820: Make additionalMongod config nullable

### LINKED ISSUE #312: Invalid value: "null": spec.additionalMongodConfig in body must be of type object: "null"'
**What did you do to encounter the bug?**
1.  Perform steps in https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md
2.  Change the members from 3 to 1 in deploy/crds/mongodb.com_v1_mongodbcommunity_cr.yaml
2.  Perform steps in https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md
3.  When running kubectl get mongodbcommunity --namespace <my-namespace>, it will report that it Failed
4.  Add -o yaml to the end  of the above command to see the error message:
```
status:
  currentMongoDBMembers: 1
  currentStatefulSetReplicas: 1
  message: 'Error setting annotations: MongoDBCommunity.mongodb.com "example-mongodb"
    is invalid: spec.additionalMongodConfig: Invalid value: "null": spec.additionalMongodConfig
    in body must be of type object: "null"'
  mongoUri: ""
  phase: Failed
```
**What did you expect?**
It should not be in a state of failure

**What happened instead?**
See error above

**Operator Information**
commit df0004a9036509baf37bbc34018b1d1432b9d53d (HEAD -> master, origin/master, origin/HEAD)
Author: Cian Hatton
Date:   Mon Feb 1 15:54:20 2021 +0000

    Fix CRD Generation (#303)

**Kubernetes Cluster Information**
minikube v1.17.1

`kubectl describe` output:
```
kubectl describe mongodbcommunity -n mongodb
Name:         example-mongodb
Namespace:    mongodb
Labels:       <none>
Annotations:  mongodb.com/v1.hasLeftReadyStateAnnotationKey: false
              mongodb.com/v1.lastVersion: 4.2.6
API Version:  mongodb.com/v1
Kind:         MongoDBCommunity
Metadata:
  Creation Timestamp:  2021-02-01T21:13:23Z
  Generation:          5
  Managed Fields:
    API Version:  mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:members:
        f:security:
          .:
          f:authentication:
            .:
            f:modes:
        f:type:
        f:version:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-02-01T21:31:33Z
    API Version:  mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:mongodb.com/v1.hasLeftReadyStateAnnotationKey:
          f:mongodb.com/v1.lastVersion:
      f:spec:
        f:additionalMongodConfig:
        f:security:
          f:tls:
            .:
            f:caConfigMapRef:
              .:
              f:name:
            f:certificateKeySecretRef:
              .:
              f:name:
            f:enabled:
            f:optional:
        f:statefulSet:
          .:
          f:spec:
            .:
            f:selector:
            f:serviceName:
            f:template:
              .:
              f:metadata:
                .:
                f:creationTimestamp:
              f:spec:
                .:
                f:containers:
            f:updateStrategy:
        f:users:
      f:status:
        .:
        f:currentMongoDBMembers:
        f:currentStatefulSetReplicas:
        f:message:
        f:mongoUri:
        f:phase:
    Manager:         mongodb-kubernetes-operator
    Operation:       Update
    Time:            2021-02-01T21:31:33Z
  Resource Version:  5134
  UID:               c48732da-10b9-4423-ac15-0b66a8aa6a17
Spec:
  Members:  1
  Security:
    Authentication:
      Modes:
        SCRAM
    Tls:
      Ca Config Map Ref:
        Name:
      Certificate Key Secret Ref:
        Name:
      Enabled:   false
      Optional:  false
  Stateful Set:
    Spec:
      Selector:      <nil>
      Template:
        Metadata:
          Creation Timestamp:  <nil>
        Spec:
          Containers:  <nil>
      Update Strategy:
  Type:  ReplicaSet
  Users:
    Db:    admin
    Name:  my-user
    Password Secret Ref:
      Name:  my-user-password
    Roles:
      Db:                           admin
      Name:                         clusterAdmin
      Db:                           admin
      Name:                         userAdminAnyDatabase
    Scram Credentials Secret Name:  my-scram
  Version:                          4.2.6
Status:
  Current Mongo DB Members:       1
  Current Stateful Set Replicas:  1
  Message:                        Error setting annotations: MongoDBCommunity.mongodb.com "example-mongodb" is invalid: spec.additionalMongodConfig: Invalid value: "null": spec.additionalMongodConfig in body must be of type object: "null"
  Mongo Uri:
  Phase:                          Failed
Events:                           <none>
```

### PR DESCRIPTION
**Pull request by chatton**
### All Submissions:

* [n/a] Have you opened an Issue before filing this PR?
* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [X] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #312

This PR makes the additional mongod field nullable in order to prevent the presence of the field in all resource specifications.

### CODE REVIEW

File: test/e2e/e2eutil.go [hunk 1]
```diff
@@ -162,9 +162,6 @@ func NewTestMongoDB(name string, namespace string) (mdbv1.MongoDBCommunity, mdbv
 					Modes: []mdbv1.AuthMode{"SCRAM"},
 				},
 			},
-			AdditionalMongodConfig: mdbv1.MongodConfiguration{
```
Comment (chatton) [inline test/e2e/e2eutil.go:165]: ensure our tests are passing "null" as the value.

**Review by bznein — APPROVED** [review]
LGTM great stuff!
