### PR TITLE
CLOUDP-69096: Implement correct scale down logic

### LINKED ISSUE #136: Pods crashed and can't start back with replicas number from 3 to 1
Hello, 

I got a weird issue where my mongo db can't start. The pods were running before (and crashed?) and while trying to restart, the `mongodb-agent` container is marked as failing starting.

If I delete everything (claimed volumes and the mongodb resource) everything will start and run correctly, but after some time, the pods did stop and can't restart.

_Note: I had a 3 replicas and scale down to 1 for budget reason, can it be the cause?_

The resource:
```yaml
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: order-db
  namespace: mongodb
spec:
  members: 1 # was 3
  type: ReplicaSet
  version: 4.2.8
```

The `mongodb-agent` logs are (_cut_):
```
[2020-08-11T08:49:01.281-00] [.info] [main/components/agent.go:LoadClusterConfig:219] [08:49:01.281] clusterConfig unchanged

[2020-08-11T08:49:02.235-00] [.info] [cm/mongoctl/processctl.go:Update:3298] <order-db-0> [08:49:02.235] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 3}]}] and upsert=true on local.clustermanager

[2020-08-11T08:49:02.271-00] [.info] [cm/director/director.go:computePlan:279] <order-db-0> [08:49:02.271] ... process has a plan : WaitPrimary,RsReconfig

<order-db-0> [08:49:02.270] ... process has a plan : WaitPrimary,RsReconfig

<order-db-0> [08:49:02.272] Running step 'WaitPrimary' as part of move 'WaitPrimary'

[2020-08-11T08:49:02.272-00] [.info] [cm/director/director.go:executePlan:867] <order-db-0> [08:49:02.272] Running step 'WaitPrimary' as part of move 'WaitPrimary'

[2020-08-11T08:49:02.272-00] [.info] [cm/director/director.go:tracef:772] <order-db-0> [08:49:02.272] Precondition of 'WaitPrimary' applies because
[All the following are true:
    ['currentState.NeedToStepDownCurrentPrimary' = false]
    ['currentState.Up' = true]
]

[2020-08-11T08:49:02.274-00] [.info] [cm/director/director.go:planAndExecute:563] <order-db-0> [08:49:02.274] Step=WaitPrimary as part of Move=WaitPrimary in plan failed : <order-db-0> [08:49:02.274] Postcondition not yet met for step WaitPrimary because ['currentState.IsPrimary' = false].
```

The `mongod` container logs are (_cut_):
```
2020-08-11T08:55:11.164+0000 I  CONNPOOL [Replication] Connecting to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017

2020-08-11T08:55:12.225+0000 I  CONNPOOL [Replication] Connecting to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017

2020-08-11T08:55:12.239+0000 I  REPL_HB  [replexec-0] Heartbeat to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017 failed after 2 retries, response status: HostUnreachable: Error connecting to order-db-1.order-db-svc.mongodb.svc.cluster.local:27017 :: caused by :: Could not find address for order-db-1.order-db-svc.mongodb.svc.cluster.local:27017: SocketException: Host not found (authoritative)
```

Do you have any idea ? 

Thanks,

### PR DESCRIPTION
**Pull request by chatton**
### All Submissions:

* [ ] Have you opened an Issue before filing this PR?
* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [X] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #136

This PR updates the operator to correctly scale down the deployment. Previously we updated the automation config and the stateful set at the same time, resulting in reducing the StatefulSet size while the agents were still trying to find members of the replica set that no longer exist.

The readiness probe was updated to check to see if the host was removed from the automation config. If so, it is no longer ready. We now reply on k8s to kill the pod once it has been removed from the replica set.

Unfortunately this current implementation takes a long time to start, as we need to wait `failureThreshold` failures, until the pods start being killed.

Because it takes so long, for now I've commented out the scale down code in our e2e and added a new test that only performs a scale down to reduce test time but ensure we are still testing scale down.

### CODE REVIEW

File: pkg/apis/mongodb/v1/mongodb_types.go [hunk 1]
```diff
@@ -298,6 +298,30 @@ func (m MongoDB) GetFCV() string {
...
+	current, desired int
+}
+
+func (a automationConfigReplicasScaler) DesiredReplicas() int {
+	return a.desired
+}
+
+func (a automationConfigReplicasScaler) CurrentReplicas() int {
+	return a.current
+}
```
Comment (chatton) [inline pkg/apis/mongodb/v1/mongodb_types.go:323]: re-use existing interface to allow us to get the correct number of automation config members each reconciliation (we will get all of them on first creation, otherwise we scale up/down one at a time)

File: deploy/operator.yaml [hunk 2]
```diff
@@ -31,7 +31,8 @@ spec:
             - name: OPERATOR_NAME
               value: "mongodb-kubernetes-operator"
             - name: AGENT_IMAGE # The MongoDB Agent the operator will deploy to manage MongoDB deployments
-              value: quay.io/mongodb/mongodb-agent:10.19.0.6562-1
+              value: quay.io/mongodb/mongodb-agent-dev:scaledown
```
Comment (chatton) [inline deploy/operator.yaml:34]: this image is the same as the previous one, but just with a new readiness probe, I will create a separate PR once this is no longer a dev image.

File: agent/Dockerfile [hunk 3]
```diff
@@ -19,9 +19,9 @@ RUN mkdir -p agent \
     && chmod -R +r /var/lib/automation/config \
     && rm agent/mongodb-agent.tar.gz \
     && rm -r mongodb-mms-automation-agent-*
-
 RUN mkdir -p /var/lib/mongodb-mms-automation/probes/ \
-    && curl --retry 3 https://readinessprobe.s3-us-west-1.amazonaws.com/readiness -o /var/lib/mongodb-mms-automation/probes/readinessprobe \
+#    && curl --retry 3 https://readinessprobe.s3-us-west-1.amazonaws.com/readiness -o /var/lib/mongodb-mms-automation/probes/readinessprobe \
+    && curl --retry 3 https://readiness-probe-scale-test.s3.amazonaws.com/readiness -o /var/lib/mongodb-mms-automation/probes/readinessprobe \
```
Comment (chatton) [inline agent/Dockerfile:24]: Will update this again once I've moved the readiness probe to the correct bucket

File: pkg/controller/mongodb/replicaset_controller_test.go [hunk 4]
```diff
@@ -424,13 +424,16 @@ func TestReplicaSet_IsScaledDown_OneMember_AtATime_WhenItAlreadyExists(t *testin
...
 	err = mgr.GetClient().Get(context.TODO(), mdb.NamespacedName(), &mdb)
 	assert.NoError(t, err)
 
 	assert.Equal(t, true, res.Requeue)
-	assert.Equal(t, 4, mdb.Status.Members)
+	assert.Equal(t, 4, mdb.Status.CurrentReplicaSetMembers)
+
+	makeStatefulSetReady(t, mgr.GetClient(), mdb)
 
 	makeStatefulSetReady(t, mgr.GetClient(), mdb)
```
Comment (bznein) [inline pkg/controller/mongodb/replicaset_controller_test.go:438]: Duplicated by mistake?

File: pkg/controller/mongodb/replicaset_controller_test.go [hunk 5]
```diff
@@ -472,7 +475,9 @@ func TestReplicaSet_IsScaledUp_OneMember_AtATime_WhenItAlreadyExists(t *testing.
 
 	assert.NoError(t, err)
 	assert.Equal(t, true, res.Requeue)
-	assert.Equal(t, 4, mdb.Status.Members)
+	assert.Equal(t, 4, mdb.Status.CurrentReplicaSetMembers)
+
+	makeStatefulSetReady(t, mgr.GetClient(), mdb)
 
 	makeStatefulSetReady(t, mgr.GetClient(), mdb)
```
Comment (bznein) [inline pkg/controller/mongodb/replicaset_controller_test.go:482]: Duplicated by mistake?

**Review by bznein — APPROVED** [review]
LGTM! Massive work, just a very small comment!

File: pkg/apis/mongodb/v1/mongodb_types.go [hunk 6]
```diff
@@ -201,8 +201,11 @@ type AuthMode string
 type MongoDBStatus struct {
 	MongoURI string `json:"mongoUri"`
 	Phase    Phase  `json:"phase"`
-	Members  int    `json:"members"`
-	Message  string `json:"message,omitempty"`
+
+	CurrentStatefulSetReplicas int `json:"currentStatefulSetReplicas"`
+	CurrentReplicaSetMembers   int `json:"currentReplicaSetMembers"`
```
Comment (rodrigovalin) [inline pkg/apis/mongodb/v1/mongodb_types.go:206]: Unfortunately there's a name clash between MongoDB ReplicaSet and Kubernetes' Replica Set and this one is actually Mongo's version of it, but not StatefulSet, which correspond to the Kubernetes object.

This will be super confusing at people looking at a status at any given time...

I would definitely vote for:

```golang
	CurrentStatefulSetReplicas int `json:"currentStatefulSetReplicas"`
	CurrentMongoDBMembers   int `json:"currentMongoDBMembers"` 
```

File: pkg/controller/mongodb/replica_set_controller.go [hunk 7]
```diff
@@ -262,6 +283,7 @@ func (r *ReplicaSetReconciler) Reconcile(request reconcile.Request) (reconcile.R
 	if err := r.resetStatefulSetUpdateStrategy(mdb); err != nil {
 		return status.Update(r.client.Status(), &mdb,
 			statusOptions().
+				withAutomationConfigMembers(mdb.AutomationConfigMembersThisReconciliation()).
```
Comment (rodrigovalin) [inline pkg/controller/mongodb/replica_set_controller.go:286]: Currently in the status we have members for "statefulset" (kubernetes) and "replicaset" (mongodb), but this API for the statusOptions builder accepts a "withAutomationConfigMembers" which I'm not sure which one it corresponds.

File: pkg/controller/mongodb/mongodb_status_options.go [hunk 8]
```diff
@@ -99,18 +80,35 @@ type messageOption struct {
...
+		zap.S().Debug(m.message.messageString)
 	}
 }
 
 func (m messageOption) GetResult() (reconcile.Result, error) {
-	return okResult()
+	return result.OK()
+}
+
+func (o *optionBuilder) withAutomationConfigMembers(members int) *optionBuilder {
```
Comment (rodrigovalin) [inline pkg/controller/mongodb/mongodb_status_options.go:100]: Although this API seems super ergonomic, it is not :)

There's no way (easy way) to see **which attribute on the `status` this function will end up modifying**.

If I call `withAutomationConfigMembers(n)`, will it end up doing `status.currentStatefulSetReplicas = n` or `status.currentReplicaSetMembers = n`?

Comment (rodrigovalin) [reply pkg/controller/mongodb/mongodb_status_options.go:100]: From a developer's perspective, it would be as easy as to explicitly describe which `status` attribute this function is supposed to change.

```golang
// withAutomationConfigMembers sets `status.someImportantAttribute`.
func withAutomationConfigMembers () {}

**Review by rodrigovalin — COMMENTED** [review]
Great work!

My only concern is related to the confusing status attributes, one related to MongoDB Replica Set members and the other one related to Kubernetes StatefulSet members. On top of that the API to change these attributes uses a different set of names (automation config members vs statefulset replicas).

My proposal is to change:

* status.replicaSetMembers -> status.mongoDBMembers
* withAutomationConfigMembers -> withMongoDBMembers

This is completely subjective so I would like to hear @bznein opinion on this.

File: pkg/apis/mongodb/v1/mongodb_types.go (hunk 6 above)
Comment (bznein) [reply pkg/apis/mongodb/v1/mongodb_types.go:206]: I don't have a strong opinion on this but I agree this sounds clearer 👍🏻
